version: "2.4"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin -h 'localhost' -u root -p010203 ping --silent",
        ]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "010203"
      MYSQL_DATABASE: rental_app
      MYSQL_USER: tester1
      MYSQL_PASSWORD: test
  backend:
    container_name: backend
    image: rental_app_backend
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: ./backend
      target: dev
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./backend/src:/usr/app/src:delegated
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: mysql
      DB_NAME: rental_app
      DB_USER: tester1
      DB_PASSWORD: test
      JWT_SALT: T3ST
  frontend:
    container_name: frontend
    image: rental_app_frontend
    tty: true
    build:
      context: ./frontend
      target: dev
    ports:
      - 3001:3000
      - 9230:9229
      - 35729:35729
    volumes:
      - ./frontend/src:/usr/app/src:delegated
    environment:
      REACT_APP_NODE_ENV: development
      REACT_APP_API_ENDPOINT: "http://localhost:3000"
      REACT_APP_GOOGLE_MAPS_API_KEY: "YOUR-KEY"
      REACT_APP_GOOGLE_GEOCODE_API_KEY: "YOUR-KEY"

volumes:
  mysqldata:
