export const API_ENDPOINT = process.env.REACT_APP_API_ENDPOINT;
export const GOOGLE_MAPS_KEY = process.env.REACT_APP_GOOGLE_MAPS_API_KEY;
export const GOOGLE_GEOCODE_KEY = process.env.REACT_APP_GOOGLE_GEOCODE_API_KEY;
